#!/bin/bash
# vim: set ft=sh

set -e -x

FINAL_RELEASE_TARBALL=$PWD/final-release-tarball
FINAL_RELEASE_REPO=$PWD/final-release-repo


VERSION=$(cat ./version/number)
if [ -z "$VERSION" ]; then
  echo "missing version number"
  exit 1
fi

git clone ./custom-res-concourse-boshrelease $FINAL_RELEASE_REPO

echo "$BOSH_PRIVATE_CONFIG" > $FINAL_RELEASE_REPO/config/private.yml

cd $FINAL_RELEASE_REPO

RELEASE_YML=$PWD/releases/custom-res-concourse-boshrelease/custom-res-concourse-boshrelease-${VERSION}.yml
FINAL_RELEASE_TGZ=$FINAL_RELEASE_TARBALL/concourse-${VERSION}.tgz

# work-around Go BOSH CLI trying to rename blobs downloaded into ~/.root/tmp
# into release dir, which is invalid cross-device link
export HOME=$PWD

git config --global user.email "ci@localhost"
git config --global user.name "CI Bot"

if ! [ -e ${RELEASE_YML} ]; then
  echo "Creating final release"
  bosh -n create-release  --version "$VERSION" --final
  git add -A
  git commit -m "release v${VERSION}"
  git tag -f "v${VERSION}"
fi


bosh -n create-release --tarball ${FINAL_RELEASE_TGZ} ${RELEASE_YML}
