---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/bosh-cli

inputs:
- name: custom-res-concourse-boshrelease
- name: resource-image
- name: resource-repo

outputs:
- name: bumped-custom-res-concourse-boshrelease

params:
  RESOURCE_NAME:
  BOSH_PRIVATE_CONFIG:

run:
  path: custom-res-concourse-boshrelease/ci/scripts/bump-resource-package
