---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/bosh-cli

inputs:
- name: custom-res-concourse-boshrelease
- name: version

outputs:
- name: final-release-repo
- name: final-release-tarball

run:
  path: custom-res-concourse-boshrelease/ci/scripts/finalize-release

params:
    RESOURCE_NAME:
