---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: getourneau/alpine-bash-git

inputs:
  - name: custom-res-concourse-boshrelease
  - name: release-repo
  - name: release-repo-master

outputs:
  - name: final-release-repo

run:
  path: custom-res-concourse-boshrelease/ci/scripts/merge-master-to-develop

params:
  MASTER_BRANCH:
  GIT_USERNAME:
  GIT_EMAIL:
  MERGED_REPO: final-release-repo
