resources:
- name: docker-slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource


- name: git-slack-notification
  type: git
  source:
    branch: master
    uri:  https://github.com/cloudfoundry-community/slack-notification-resource.git


- name: custom-res-concourse-boshrelease-dev
  type: git
  source:
    branch: develop
    private_key: {{private-key-github-concourse}}
    uri: git@github.com:shinji62/custom-res-concourse-boshrelease.git




- name: custom-res-concourse-boshrelease
  type: git
  source:
    branch: master
    private_key: {{private-key-github-concourse}}
    uri: git@github.com:shinji62/custom-res-concourse-boshrelease.git



- name: gh-release
  type: github-release
  source:
    user: shinji62
    repository: custom-res-concourse-boshrelease
    access_token: {{github-access-token}}

- name: version
  type: semver
  source:
    driver: git
    uri: git@github.com:shinji62/custom-res-concourse-boshrelease.git
    branch: version
    file: version
    private_key: {{private-key-github-concourse}}
    git_user: {{concourse-user-gitinfo}}



jobs:
- name: bump-slack-resource
  serial: true
  plan:
  - get: docker-slack-notification
    params: {rootfs: true}
    trigger: true
  - get: custom-res-concourse-boshrelease-dev
  - get: git-slack-notification
  - task: bump-package
    input_mapping:
      custom-res-concourse-boshrelease:  custom-res-concourse-boshrelease-dev
      resource-image: docker-slack-notification
      resource-repo: git-slack-notification
    file: custom-res-concourse-boshrelease/ci/task/bump-resource-package.yml
    params:
      RESOURCE_NAME: slack-resource
      BOSH_PRIVATE_CONFIG: {{custom_rest_release_private_config}}
      GIT_USERNAME: {{github-username}}
      GIT_EMAIL:  {{github-email}}
  - put: custom-res-concourse-boshrelease-dev
    params: {repository: bumped-custom-res-concourse-boshrelease, rebase: true}


- name: minor
  plan:
  - do:
    - { get: version, trigger: false, params: {bump: minor} }
    - { put: version,                 params: {file: version/number} }

- name: major
  plan:
  - do:
    - { get: version, trigger: false, params: {bump: major} }
    - { put: version,                 params: {file: version/number} }




- name: shipit
  plan:
  - get: custom-res-concourse-boshrelease
  - get: version
  - task: finalize-bosh-release
    file: custom-res-concourse-boshrelease/ci/tasks/finalize-release.yml
    params:
      GIT_USERNAME: {{github-username}}
      GIT_EMAIL:  {{github-email}}
      BOSH_PRIVATE_CONFIG: {{custom_rest_release_private_config}}
  - put: custom-res-concourse-boshrelease
    params:
      repository: final-release-repo
      rebase: true
  - put: gh-release
    params :
      name: version/number
      tag: version/number
      globs:
      - final-release-tarball/*



- name: downstream-master
  serial: true
  plan:
  - aggregate:
    - get: custom-res-concourse-boshrelease
    - get: release-repo-master
      resource: custom-res-concourse-boshrelease
      trigger: true
      passed: [shipit]
    - get: release-repo
      resource:  custom-res-concourse-boshrelease-dev
  - task: merge-master-to-develop
    file: custom-res-concourse-boshrelease/ci/tasks/merge-master-to-develop.yml
    params:
      GIT_USERNAME: {{github-username}}
      GIT_EMAIL:  {{github-email}}
  - put: custom-res-concourse-boshrelease-dev
    params:
      repository: final-release-repo
      rebase: true
